version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: marco
      MYSQL_USER: marco_user
      MYSQL_PASSWORD: your_mysql_password
